version: "3"

services:
  # geth-mainnet:
  #   build:
  #     context: ./geth
  #     dockerfile: Dockerfile

  geth-devnet:
    # build:
    #   context: ./geth
    #   dockerfile: Dockerfile
    image: geth:latest
    volumes:
      - ~/workspace/pvt-bc/geth/data:/app/data
      - ~/workspace/pvt-bc/geth/keystore:/app/data/keystore
    command: ["--datadir", "/app/data", "--dev", "--dev.period", "14"]

  geth-client:
    # build:
    #   context: ./geth
    #   dockerfile: Dockerfile
    image: geth:latest
    command: ["attach", "http://geth-devnet:8545"]

  # geth-signer:
  #   build:
  #     context: ./geth
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ~/workspace/pvt-bc/geth/local:/app

  # truffle:
  #   build:
  #     context: ./truffle
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ~/workspace/pvt-bc/truffle/app:/app
